### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wuxiaoqiang625** [Android-Mu/SelectPhotoDemo#2]
01-17 10:43:59.194 29701-30457/com.example.mjj.selectphotodemo E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
                                                                                 Process: com.example.mjj.selectphotodemo, PID: 29701
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                                     at com.example.mjj.selectphotodemo.utils.ImageLoader.cacheBitmap2Disk(ImageLoader.java:314)
                                                                                     at com.example.mjj.selectphotodemo.utils.ImageLoader.access$1300(ImageLoader.java:32)
                                                                                     at com.example.mjj.selectphotodemo.utils.ImageLoader$DiskCacheThread.run(ImageLoader.java:285)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by stancyf** [comment]
me too
